services:
  pihole:
    build: .
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq.d:
